### ISSUE TITLE
Encoding error UTF-8

### ISSUE THREAD

**Issue by fabian9019** [perdian/macosappbundler-maven-plugin#13]
By using the plugin as shown below:
			`<plugin>`
				`<groupId>de.perdian.maven.plugins</groupId>`
				`<artifactId>macosappbundler-maven-plugin</artifactId>`
				`<version>1.7.0</version>`
				`<configuration>`
					`<jdk>`
						`<include>true</include>`
					`</jdk>`
					`<plist>`
			`<CFBundleIconFile>/src/main/resources/images/image.icns</CFBundleIconFile>`
						`<JVMMainClassName>test.javafxTest.Main</JVMMainClassName>`
						`<CFBundleDisplayName>TEST</CFBundleDisplayName>`
					`</plist>`
					`<dmg>`
						`<generate>true</generate>`
						`<dmgFileName>TEST</dmgFileName>`
						`<appendVersion>true</appendVersion>`
					`</dmg>`
				`</configuration>`
				`<dependencies>`
					`<dependency>`
						`<groupId>commons-io</groupId>`
						`<artifactId>commons-io</artifactId>`
						`<version>2.6</version>`
					`</dependency>`
				`</dependencies>`
				`<executions>`
					`<execution>`
						`<phase>package</phase>`
						`<goals>`
							`<goal>bundle</goal>`
						`</goals>`
					`</execution>`
				`</executions>`
			`</plugin>`

The JDK is included but when I run the .app application it runs normally except that the JDK loads the UTF-8 raw application, so the application is displayed with special characters.
I can't find how to correct this problem.
![image](https://user-images.githubusercontent.com/7716797/80025181-d5396480-84a5-11ea-8a2c-eeee0e07ce88.png)

Does anyone have any ideas?

**Comment by perdian** [comment]
Yes, I have experienced the same behavior. 

It doesn't seem to be related to the launcher but a defect in the JavaFX core libraries, see https://github.com/openjdk/jfx/pull/55 and https://bugs.openjdk.java.net/browse/JDK-8234916 for details.

My personal workaround for my applictions is this:

```java
Scene scene = new Scene(mainPane);
scene.getStylesheets().add("META-INF/stylesheet.css");
```

The stylesheet itself then defines the font(s) to be used:

```css
/*
 * We need to explicitely use a dedicated font until the following issue is resolved:
 * https://github.com/openjdk/jfx/pull/55
 */
.root {
    -fx-font-family: Helvetica, Arial, SansSerif;
}
```
