### ISSUE TITLE
JVMMainModuleName example

### ISSUE THREAD

**Issue by cemartins** [perdian/macosappbundler-maven-plugin#16]
Hi. Great job with this plugin. I love it!
I am using it, but unfortunately my application is not starting - cannot find the main class.
I suspect it is because it is a Java 11 application.

It would be nice if you included an example of the parameter `JVMMainModuleName` in your README. And also some debugging tips in case the app does not start.

**Comment by perdian** [comment]
I've added an example for how to use a Java 9+ module based application to the [README](https://github.com/perdian/macosappbundler-maven-plugin/blob/master/README.md).

There is also a new example application showing how to configure the plugin for a module based application:
https://github.com/perdian/macosappbundler-maven-plugin/tree/master/example-modulepath
