### ISSUE TITLE
App is not opening with doble click but is opening from shell

### ISSUE THREAD

**Issue by giansluca** [perdian/macosappbundler-maven-plugin#17]
Hi,
after building (normal, no module) with maven i'm facing this issue:
I can run the app from shell with command: open -a myprogramm.app,  but nothing happens when i try to launch it clicking on it... no errors, no messages.

jdk installed is openjdk 11 (with brew)
os Catalina

Thanks!

**Comment by perdian** [comment]
That's a pretty hard description to start debugging on.

Can you please provide a reproducable example?

You can also run the executable directly from the command line and take a look at the console output:

```
$ /Applications/YourApplication.app/Contents/MacOS/JavaLauncher
```

**Comment by giansluca** [comment]
Hi thanks! Yes i found the issue, it was my fault, running directly the executable gave me more info and the error. i was not passing in the correct way parameters to main. 

Now the app starts correctly, although i got sometime a weird app crash.
It looks not related to the app because it never happens running the app under the IDE ... i'm ivestigating.

It is a graphical osx window error
Thanks for your help!

<img width="968" alt="Screenshot 2020-10-13 at 16 52 59" src="https://user-images.githubusercontent.com/11060553/95877600-914c5b80-0d74-11eb-8f5e-f1737131475e.png">
