### ISSUE TITLE
Swing Colors Change

### ISSUE THREAD

**Issue by jonathanlocke** [perdian/macosappbundler-maven-plugin#18]
Enjoying this plugin. So easy to make a MacOS app out of my Java Swing app. 

When I create a .app with the bundler plugin for my modular Java Swing app it works fine, but the button colors and some other UI colors wind up quite different from when I run it from the IDE or from an executable JAR file. It seems to be ignoring the colors I've set and choosing some rather bad colors instead. It's quite strange. Any idea what might be going on?

Thanks,

    Jon

**Comment by perdian** [comment]
I've had a few strange experiences with fonts so far, but never with colors. How exactly do you define the colors?

**Comment by perdian** [comment]
No action for 14 days, closing this issue. Feel free to reopen if you have more data and a testcase to reproduce the behaviour.
