### ISSUE TITLE
Requesting way to use existing JAR 

### ISSUE THREAD

**Issue by Trainzack** [perdian/macosappbundler-maven-plugin#21]
I'm currently writing a project that uses JavaFX to display windows. Some of the resources it uses to do that (.fxml files) were not being included in the jar, so I used a different Maven plugin to shade the jar to include those resources.

Now that I want to create MacOS executables, it would be most convenient for me to simply package that JAR in the executable, rather than relying on this plugin to get all of the resources properly. Is this at all possible?

**Comment by perdian** [comment]
> Is this at all possible?

Well, of course it's *possible* - but it's not the reason why this plugin exists.

This plugin exists to package a macOS bundle from a Java application that conforms to the default setup for a Maven project (Sources in `src/main/java`, resources in `src/main/resources`, dependencies declared `pom.xml` and so on).

I definitely see your use case but this is not what this plugin was designed to accomplish.

**Comment by Trainzack** [comment]
Alright then, I guess I'll have to bite the bullet and refactor my program to adhere to the standard. Thanks for the quick reply!
