### ISSUE TITLE
Dynamic library does not work with JRE 14

### ISSUE THREAD

**Issue by ashesfall** [perdian/macosappbundler-maven-plugin#22]
![image](https://user-images.githubusercontent.com/2320397/113083762-a0439080-9191-11eb-975c-13d48b6cd5a1.png)

Any idea what could cause this?

**Comment by perdian** [comment]
Looks like the content of the packaged JDK isn't what the launcher expects.

Can you please launch your application directly from the console and post the debugging output?

```shell
$ /Volumes/RingsDesktop/RingsDesktop.app/Contents/MacOS/JavaLauncher
```

Please also list the content of your app directory:

```shell
$ tree /Volumes/RingsDesktop/RingsDesktop.app/
```

**Comment by ashesfall** [comment]
So it does seem to work without specifying a JDK location. I think maybe to specify one I was supposed to use jdkfolder/Contents rather than jdkfolder/? Is that noted in the docs?

Also, if you are on the M1 you need to be sure to only build an X86_64 or it will try and start the jdk without rosetta and that doesn't work. Both of these facts should probably be noted in the readme, but otherwise this is an AWESOME project. Thank you so much. Are you accepting donations for continued development?

**Comment by perdian** [comment]
> So it does seem to work without specifying a JDK location. I think maybe to specify one I was supposed to use jdkfolder/Contents rather than jdkfolder/? Is that noted in the docs?

Did you create the application bundle with the JDK using the provided configuration parameters?

```xml
    ...
    <configuration>
      <jdk>
        <include>true</include>
        <location>/where/your/jdk/is/installed</location>
      </jdk>
    </configuration>
    ...
```

This requires the JDK to be available at the specified location **at the time the plugin is invoked.

```xml
    ...
    <configuration>
      <jdk>
        <include>true</include>
      </jdk>
    </configuration>
    ...
```

This will infer the location of the JDK from the JDK that is used by Maven while building the application bundle.

I didn't do extensive testing on the inclusion functionalities (as I'm not using it). I tried it a while back but didn't really verify it with newer JDKs so it could very well be that it's not up-to-date.

> Also, if you are on the M1 you need to be sure to only build an X86_64 or it will try and start the jdk without rosetta and that doesn't work. Both of these facts should probably be noted in the readme

I'm a bit confused - not sure I understand you correctly here. 

The universal binary was introduced in the [1.10 release](https://github.com/perdian/macosappbundler-maven-plugin/compare/release-1.9.0...release-1.10.0). Does the ARM binary not work with an X84_64 JDK or does it not work at all?

Unfortunately I don't have an M1 Mac myself so it's hard for me to actually test this. You do have the option to configure the plugin to **not** use the ARM version but force the X86_64 version, even on M1 Macs (https://github.com/perdian/macosappbundler-maven-plugin#native-binary-selection) 

```xml
...
    <configuration>
      <nativeBinary>X86_64</nativeBinary>
    </configuration>
...
```

> but otherwise this is an AWESOME project. Thank you so much.

Thanks for the feedback. I love seeing that what I originally built for myself is useful to others as well.

> Are you accepting donations for continued development?

I haven't really given this much thought but if you insist I'm sure there is a way 😀

[![Donate](https://www.paypalobjects.com/en_US/DK/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=P94BEUKLPMEFJ)

**Comment by ashesfall** [comment]
Forcing X86_64 did work for me, and to answer your query, it seems universal binary is fine on other machines (probably running as X86_64 anyway, on the ones I have here), but on the M1 it tries to run the JDK natively [I assume], which doesn't work. It has to know that it **requires** X86_64 so that it can run rosetta and properly load the JDK (which was not compiled for M1).

For some reason it still doesn't work when I specify a JVM. My configuration is below.

This is not urgent though, the default mechanism is fine.

               ```
 <configuration>
                    <plist>
                        <CFBundleIconFile>resources/rings.icns</CFBundleIconFile>
                        <CFBundleName>Rings RC</CFBundleName>
                        <CFBundleDisplayName>Rings RC</CFBundleDisplayName>
                        <CFBundleDevelopmentRegion>English</CFBundleDevelopmentRegion>
                        <JVMMainClassName>com.almostrealism.Rings</JVMMainClassName>
                        <JVMVersion>14+</JVMVersion>
                        <JVMOptions>
                            <string>-DAR_HARDWARE_PLATFORM=cpu</string>
                        </JVMOptions>
                    </plist>
                    <nativeBinary>X86_64</nativeBinary>
                    <jdk>
                        <include>true</include>
                        <location>/Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk</location>
                    </jdk>
                </configuration>
```

![image](https://user-images.githubusercontent.com/2320397/113220288-c91e6100-9237-11eb-8171-d283ae9b9720.png)

**Comment by perdian** [comment]
> Forcing X86_64 did work for me, and to answer your query, it seems universal binary is fine on other machines (probably running as X86_64 anyway, on the ones I have here), but on the M1 it tries to run the JDK natively [I assume], which doesn't work. It has to know that it **requires** X86_64 so that it can run rosetta and properly load the JDK (which was not compiled for M1).

I  did a bit of research and from what I found there currently aren't any ARM JDKs out there yet. As the JDK is invoked natively from within the launcher, the launcher and the JDK must use the same architecture, so an ARM launcher with an X86_64 JDK will not work, which also explains why (until there is a real ARM JDK) you have to explicitly define the X84_64 launcher when building the application.

From what I see there is nothing that can be done about that.

> Neither of these started without the error message originally posted

Ah okay, the picture becomes a bit clearer. Looks like the files copied into the bundle are taken from the wrong directory.

Could you post your `configuration` element?

```xml
    <configuration>
      <jdk>
        <include>true</include>
        <location>/where/your/jdk/is/installed</location>
      </jdk>
    </configuration>
```

Do you specify an explicit `location` or just use the automatic lookup of the JDK without a location?

**Comment by ashesfall** [comment]
```
                    <jdk>
                        <include>true</include>
                        <location>/Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk</location>
                    </jdk>
```
Dropping the explicit location works, so I am set for now, but I don't see why this doesn't do the same thing. And I will later want to specify other JDKs, so I can make a few versions.

**Comment by perdian** [comment]
Alright, now I can see why this is not working as expected, thanks for the example.

The JDK itself is located in `/Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk/Contents/Home` and **not** in `/Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk/` as you've specified.

When not using the `/Contents/Home` directory, the JDK is copied into the resulting binary but not in the correct form.

I think however this should be easily fixable. I'll adjust the collection mechanism so that the Maven plugin will automatically infer the `Contents/Home` directory if the parent JDK directory is set.

**Comment by perdian** [comment]
The fix is implemented and released with version [`1.10.2`](https://github.com/perdian/macosappbundler-maven-plugin/releases/tag/release-1.10.2)

Both configurations will now work correctly:

```xml
...
  <plugin>
    <groupId>de.perdian.maven.plugins</groupId>
    <artifactId>macosappbundler-maven-plugin</artifactId>
    <version>1.10.2</version>
    <configuration>
      ...
      <jdk>
        <include>true</include>
        <location>/Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk/Contents/Home</location>
      </jdk>
      ...
    </configuration>
  </plugin>
...
```

```xml
...
  <plugin>
    <groupId>de.perdian.maven.plugins</groupId>
    <artifactId>macosappbundler-maven-plugin</artifactId>
    <version>1.10.2</version>
    <configuration>
      ...
      <jdk>
        <include>true</include>
        <location>/Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk</location>
      </jdk>
      ...
    </configuration>
  </plugin>
...
```

**Comment by ashesfall** [comment]
Thank you!

**Comment by uwemock** [comment]
I just found this issue which seems to be what many of my users are experiencing.

I would have tried 1.10.2, but version 1.10.1 already requires Java 9.

Does this requirement apply to the build environment or the execution environment?

**Comment by perdian** [comment]
> Does this requirement apply to the build environment or the execution environment?

It applies to the **build** environment (when reading the JDK files from the machine where the application bundle is created).
