### ISSUE TITLE
Copy the executable to the bundle

### ISSUE THREAD

**Issue by cripson1994** [perdian/macosappbundler-maven-plugin#24]
Hi! I tried to copy the executable to the bundle using the additionalResources field, but after copying, the file lost executable privileges. Are there other ways to achieve this goal?

**Comment by perdian** [comment]
Thanks for reporting this.

Currently there is no other way to copy files into the bundle without losing the executable flag. 

I'll take a look at the copy mechanism and how to keep the flag.

**Comment by perdian** [comment]
Fixed and released as `1.12.0`.
