### ISSUE TITLE
Microphone not working on bundled application

### ISSUE THREAD

**Issue by sebouh137** [perdian/macosappbundler-maven-plugin#28]
I am unable to get the microphone input to work on an app I wrote.  When running the program through the JVM directly, the microphone works.  I suspect there is something wrong with the permissions, which may have changed when I switched over to Monterey.  

Digging through material online, I found that this is related to entitlements com.apple.security.device.microphone and com.apple.security.device.audio-input, as well as a plist property NSCameraUsageDescription.   Could you fix this, so that my bundled app can run and use the microphone?
Thanks

**Comment by sebouh137** [comment]
I found that the following modification to src/main/java/de/perdian/maven/plugins/macosappbundler/mojo/model/PlistConfiguration.java will fix this issue (essentially it's just adding NSMicrophoneUsageDescription to the allowed plist items).  I would upload a branch with this fix included, and then do a pull request, but it's not letting me upload the branch.  

diff --git a/src/main/java/de/perdian/maven/plugins/macosappbundler/mojo/model/PlistConfiguration.java b/src/main/java/de/perdian/maven/plugins/macosappbundler/mojo/model/PlistConfiguration.java
index 63ee849..8a2ec76 100644
--- a/src/main/java/de/perdian/maven/plugins/macosappbundler/mojo/model/PlistConfiguration.java
+++ b/src/main/java/de/perdian/maven/plugins/macosappbundler/mojo/model/PlistConfiguration.java
@@ -93,6 +93,9 @@ public class PlistConfiguration {
     @Parameter
     public Boolean NSSupportsAutomaticGraphicsSwitching = Boolean.TRUE;
 
+    @Parameter
+    public String NSMicrophoneUsageDescription = null;
+    
     public String toXmlString(Map<String, String> additionalValues) throws Exception {
 
         TransformerFactory transformerFactory = TransformerFactory.newInstance();
@@ -132,6 +135,7 @@ public class PlistConfiguration {
         this.appendKeyWithBoolean(dictElement, document, "NSHighResolutionCapable", this.NSHighResolutionCapable);
         this.appendKeyWithBoolean(dictElement, document, "LSUIElement", this.LSUIElement);
         this.appendKeyWithBoolean(dictElement, document, "NSSupportsAutomaticGraphicsSwitching", this.NSSupportsAutomaticGraphicsSwitching);
**+       this.appendKeyWithString(dictElement, document, "NSMicrophoneUsageDescription",** this.NSMicrophoneUsageDescription);
         for (Map.Entry<String, String> additionalValue : additionalValues.entrySet()) {
             this.appendKeyWithString(dictElement, document, additionalValue.getKey(), additionalValue.getValue());
         }

**Comment by perdian** [comment]
Hi @sebouh137 

Thanks for taking the time to add the keys 👍

I just came back from vacation so I'll take a look at your PRs within the next couple of days.

**Comment by perdian** [comment]
Released to Maven Central as `1.15.0`
