### ISSUE TITLE
App menu entries in English instead of German

### ISSUE THREAD

**Issue by uwemock** [perdian/macosappbundler-maven-plugin#3]
This might not be the right place, but some people complain that my MacOS bundled apps have a menu in English: About, Services, Hide, Hide others, Show all, Quit. I don't know if this is related to packaging or something else, but I thought this would be the right place to ask people who might know.

Any idea?

**Comment by lfuelling** [comment]
@perdian feel free to assign me to this, I'm currently having the same problem and am trying to find a solution for it.

**Comment by perdian** [comment]
> @perdian feel free to assign me to this, I'm currently having the same problem and am trying to find a solution for it.

Perfect!

**Comment by perdian** [comment]
Did some more research on this:
https://stackoverflow.com/questions/28560911/internationalization-of-native-mac-menu-bar%3E

**Comment by perdian** [comment]
Closing as it's almost a year old and there doesn't seem to be real demand for this.
