### ISSUE TITLE
Code signing support

### ISSUE THREAD

**Issue by wetneb** [perdian/macosappbundler-maven-plugin#35]
Hello,
Thanks for developing this plugin!
I wonder if you had considered adding support for code-signing the bundled application (and JRE, if embedded).
An example of the code signing process is laid out in the Gephi packaging script (written as a Maven Antrun goal):
https://github.com/gephi/gephi/blob/ac43719c48ef8b12d4dd5f3d15ef2f36443b9192/modules/application/pom.xml#L674-L822

It is a bit daunting but that is because they have some dependencies which use native code. For vanilla Java, it seems fairly straightforward.

**Comment by perdian** [comment]
Yes, might be a useful enhancement.

Some links that may be useful for future implementation:
- https://stackoverflow.com/questions/13204407/how-to-codesign-an-existing-mac-os-x-app-file-for-gatekeeper
- https://www.digicert.com/kb/code-signing/mac-os-codesign-tool.htm

**Comment by perdian** [comment]
Work in progress at: https://github.com/perdian/macosappbundler-maven-plugin/tree/feature/codesign

**Comment by perdian** [comment]
Released to Maven Central as `1.19.0`
