### ISSUE TITLE
Support to add single dependency

### ISSUE THREAD

**Issue by akuhtz** [perdian/macosappbundler-maven-plugin#37]
Hello,

Is it possible to add a single dependency (e.g. spring boot executable jar) from a different module?

I want to be able to build the jar (with all dependencies included) in a maven module A and build the DMG in a maven module B, and the content of the DMG should be the jar from maven module A.

I was trying to get this to work with this change:
https://github.com/akuhtz/macosappbundler-maven-plugin/commit/3d53f6811609004f373c33cf61005523de2c603e
But the build of my project fails with ```Command 'hdiutil' exited with status 1``` and I don't know where to start the search for the cause.

**Comment by perdian** [comment]
I'm not really sure I understand the usecase. When adding module A as dependency of module B then the DMB built within module B will contain all classes (and transitive dependencies) from module A:

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>module-b</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
          <groupId>com.example</groupId>
          <artifactId>module-a</artifactId>
          <version>1.0.0-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>de.perdian.maven.plugins</groupId>
                <artifactId>macosappbundler-maven-plugin</artifactId>
                <version>1.17.1</version>
                <configuration>
                    <plist>
                        <JVMMainClassName>com.example.YourApplication</JVMMainClassName>
                    </plist>
                    <dmg>
                        <generate>true</generate>
                    </dmg>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>bundle</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
```

> But the build of my project fails with Command 'hdiutil' exited with status 1 and I don't know where to start the search for the cause.

To build the DMG the [`hdiutil`](https://www.unix.com/man-page/osx/1/hdiutil/) command needs to be available on the machine where you're building the DMG. Is that the case? Is any more information printed to the console **why** the command fails?

Did you try running the `hdiutil` command directly after you've created the application bundle? Take a look at 

https://github.com/perdian/macosappbundler-maven-plugin/blob/429e364b6f990313e85d0072b5759435574b0bf0/src/main/java/de/perdian/maven/plugins/macosappbundler/mojo/impl/DmgGenerator.java#L121-L128 

Building the command is pretty straight-forward.

**Comment by akuhtz** [comment]
Thanks for the fast reply. 

I have created a demo project that shows the situation: https://github.com/akuhtz/app-bundle-demo

While testing I found out, that excluding the transient dependencies would solve my issue. However for bigger projects the exclusion list would be hard to maintain. Maybe a new flag to not include transient dependencies would be a solution.

**Comment by perdian** [comment]
From my point of view the main reason to use the Spring boot plugin is to create a single uber JAR where all the application classes are packaged. 

But when creating an application (either directly as an `.app` or within an `.dmg`) that actually isn't needed.

So for me the solution would be **not** to use the Spring boot repackaging but let the appbundler do it's "regular" job in making sure all the dependencies are accessible within the application.

**Comment by perdian** [comment]
... and looking at my own documentation there already is a flag to exclude the dependencies:

```
    <configuration>
        <app>
            <includeDependencies>false</includeDependencies>
        </app>
    </configuration>
```

(see https://github.com/perdian/macosappbundler-maven-plugin#dependencies-exclusion)

**Comment by akuhtz** [comment]
Yes I know, but this will exclude the dependency to ```app-module-a``` too ... The classpath folder then only contains the ```app-bundle-b``` jar (you can use the commented property in the ```pom.xml``` of ```app-bundle-b``` in my demo project).
