### ISSUE TITLE
dmgFileName is not applied if appendVersion not set false

### ISSUE THREAD

**Issue by raydac** [perdian/macosappbundler-maven-plugin#39]
by default you have appendVersion as true and it blocks use of dmgFileName and not transparent at all without plugin sources examination

**Comment by perdian** [comment]
Thanks for reporting this. Will take a closer look in https://github.com/perdian/macosappbundler-maven-plugin/tree/fix/correctly-evaluate-dmg-file-name.

**Comment by perdian** [comment]
Released to Maven Central as version `1.18.1`
