### ISSUE TITLE
jspawnhelper malformed by JDK inclusion (ie, Cannot use ProcessBuilder)

### ISSUE THREAD

**Issue by ashesfall** [perdian/macosappbundler-maven-plugin#46]
I found a very interesting edge case that I think it would probably be easy to fix.

It looks like when the JDK is included, this file Contents/Java/jdk/lib/jspawnhelper is not executable, as it is before it is copied into the bundle).

The result of this is that all attempts to use ProcessBuilder generate a Not Found error.

It took me *forever* to figure out what was going on here, finally I found this https://macosx-port-dev.openjdk.java.narkive.com/8NdCdcOt/spawning-a-process-from-an-app-packaged-with-appbundler-impossible

**Comment by perdian** [comment]
Interesting find 👍

The Maven plugin uses `copyDirectory` from `commons-io` to recursively copy the files from the JDK. Looks like `commons-io` only uses `StandardCopyOption.REPLACE_EXISTING` and **not** `COPY_ATTRIBUTES` which would be required to keep the attributes.

There is no way to customize the `copyDirectory` method so I think I'll need to do the copy process manually using the `Files.copyFile` method.

**Comment by perdian** [comment]
Released to Maven Central as [`1.20.1`](https://github.com/perdian/macosappbundler-maven-plugin/releases/tag/v1.20.1)

**Comment by perdian** [comment]
Thank you very much 🙏
