### ISSUE TITLE
Packaged App Bundle always asks for Permission to see Documents Directory

### ISSUE THREAD

**Issue by Evolinox** [perdian/macosappbundler-maven-plugin#47]
Hey there,

I've successfully bundled my program into a .app Bundle. But I've encountered a first "Issue", every time I open my App, it asks me multiple times for permissions to read the Documents Directory.

<img width="431" alt="image" src="https://github.com/perdian/macosappbundler-maven-plugin/assets/72224389/87479ad6-20e8-4a7a-a11f-dbd99b94e75f">

Does someone know a fix for this?

**Comment by perdian** [comment]
I've had this a couple of times too.

What works for me is to **always** sign the application, even if it's only the local identity via the `codesign` configuration:

```
<plugin>
  <groupId>de.perdian.maven.plugins</groupId>
  <artifactId>macosappbundler-maven-plugin</artifactId>
  <version>1.20.0</version>
  <configuration>
    ...
    <codesign>
      <identity>-</identity>
    </codesign>
    ...
  </configuration>
  ...
```
