### ISSUE TITLE
In Info.plist, LSUIElement is boolean, but should be string

### ISSUE THREAD

**Issue by SwingGuy1024** [perdian/macosappbundler-maven-plugin#50]
The LSUIElement attribute can only be true or false, or it can be missing. This suggests that it's a boolean property, but it's actually a string. (I understand that it used to be boolean, but I'm not sure about that.)

But this plugin treats it as boolean, and it doesn't work that way.

When I go into the Info.plist file and change it to this:

        <key>LSUIElement</key>
        <string>true</string>

it works properly. (It blocks my application from showing on the Dock.)

but the way the bundler handles it, it looks like this:

        <key>LSUIElement</key>
        <true/>

and it has no effect this way.

The documentation says that this is a Boolean property, but it only works when it's a String property.

**Comment by SwingGuy1024** [comment]
I tested a fix to this and checked it into my fork of this project. You can find it at https://github.com/SwingGuy1024/macosappbundler-maven-plugin. I've tested it and it works fine. (It was a simple fix.)

I may file a pull request in the future, but it's past my bedtime.

**Comment by perdian** [comment]
Fixed and release to Maven Central as `1.21.1`

**Comment by SwingGuy1024** [comment]
Thanks.
