### ISSUE TITLE
Way to include JRE in the bundle?

### ISSUE THREAD

**Issue by t-oster** [perdian/macosappbundler-maven-plugin#8]
Hi,

the federkasten version did have an option to include a previously downloaded JRE inside the app bundle. This doesn't seem to be possible here, or am I missing something?

**Comment by perdian** [comment]
Nope, right now there is no such option.

**Comment by perdian** [comment]
@t-oster FYI I looked into this and it seems pretty quick and easy to implement. Changes are already made, but not release to Maven Central yet - will do that later this week.

https://github.com/perdian/macosappbundler-maven-plugin/tree/add-option-to-include-jdk-into-application

**Comment by perdian** [comment]
I just released version `1.5.0` which includes the option to include the JDK inside the app bundle.

**Comment by t-oster** [comment]
Thank you very much. That was quick!
