### ISSUE TITLE
Change working directory

### ISSUE THREAD

**Issue by mpetersen** [perdian/macosappbundler-maven-plugin#9]
Is there a way to change the working directory? Currently, the "user.dir" is within the app bundle itself.

**Comment by perdian** [comment]
Sure, shouldn't be too difficult. Where would expect the directory to point to by default?

**Comment by mpetersen** [comment]
I think it should be the directory in which the app bundle is:

    /path/to/app/AppBundle.app

The working directory should be `/path/to/app`.

**Comment by perdian** [comment]
> I think it should be the directory in which the app bundle is:
> 
> ```
> /path/to/app/AppBundle.app
> ```
> 
> The working directory should be `/path/to/app`.

I'm not sure if that's the best way to go. If I install the bundle into `/Applications` then the *working directory* would be `/Applications` which most likely isn't what the author of the app expects.

What about other macOS app? I haven't looked deeper into that but where do they point their current directory?

**Comment by perdian** [comment]
Interesting find on StackOverflow:

> Mac apps generally can't rely on the working directory being set to anything in particular. Xcode sets it one way, launching from the Finder sets it a different way (usually to /).

https://stackoverflow.com/questions/10015770/what-do-i-set-the-working-directory-of-a-macos-app-bundle-launched-from-my-java

**Comment by mpetersen** [comment]
Interesting discussion. I think we should close this issue until requirements are more clear :-)
